### ISSUE TITLE
hot reload for backend nestjs

### ISSUE THREAD

**Issue by ethan0905** [ethan0905/ft_transcendence#14]

**Comment by ethan0905** [comment]
In order to implement this service, you must:
1- Go to your docker-compose.yml file, create a volume for your backend files. Then, go to the backend service and add the 9229 port for debbuging mode.
````yaml
  backend:
    container_name: backend_nestjs
    [...]
    ports:
       [...]
      # debugging port
      - 9229:9229
     [...]
````
2- Instead of starting the backend using `npm start`, you must use `npm run start:debug`
3- Enjoy your hot reload !
